# https://travis-ci.com/spyder-ide/conda-manager

# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

sudo: false

branches:
  only:
    - master

os:
  - osx

env:
  global:
    # Used by qthelpers to close widgets after a defined time
    - TEST_CI="True"
    # Environment variables used by astropy helpers
    - CONDA_DEPENDENCIES="anaconda-client pillow pyyaml qtawesome qtpy requests"
    - PIP_DEPENDENCIES="coveralls pytest-qt"

  matrix:
    # PyQt5
    - TRAVIS_PYTHON_VERSION=3.5 USE_QT_API=PyQt5
    - TRAVIS_PYTHON_VERSION=3.4 USE_QT_API=PyQt5
    - TRAVIS_PYTHON_VERSION=2.7 USE_QT_API=PyQt5
    # PySide2
#    - TRAVIS_PYTHON_VERSION=3.5 USE_QT_API=PySide2
#    - TRAVIS_PYTHON_VERSION=3.4 USE_QT_API=PySide2
#    - TRAVIS_PYTHON_VERSION=2.7 USE_QT_API=PySide2
    # PyQt4
    - TRAVIS_PYTHON_VERSION=3.5 USE_QT_API=PyQt4
    - TRAVIS_PYTHON_VERSION=3.4 USE_QT_API=PyQt4
    - TRAVIS_PYTHON_VERSION=2.7 USE_QT_API=PyQt4
    # PySide
#    - TRAVIS_PYTHON_VERSION=2.7 USE_QT_API=PySide

before_install:
  # Test environments for different Qt bindings
  - if [[ "$USE_QT_API" == "PyQt5" ]]; then
      export CONDA_DEPENDENCIES='qt=5.* pyqt=5.* $CONDA_DEPENDENCIES';
    elif [[ "$USE_QT_API" == "PySide2" ]]; then
      export CONDA_DEPENDENCIES='qt=5.* pyside2 $CONDA_DEPENDENCIES';
    elif [[ "$USE_QT_API" == "PyQt4" ]]; then
      export CONDA_DEPENDENCIES='qt=4.* pyqt=4.* $CONDA_DEPENDENCIES';
    elif [[ "$USE_QT_API" == "PySide" ]]; then
      export CONDA_DEPENDENCIES='qt=4.* pyside $CONDA_DEPENDENCIES';
    fi

install:
  # Use Astropy ci helpers for initial setup
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh
  - $CONDA_INSTALL ciocheck -c conda-forge
  - python setup.py develop

script:
  - ciocheck conda_manager
  - conda-manager

after_success:
  - coveralls
