# https://travis-ci.com/spyder-ide/conda-manager

language: python
sudo: false

env:
  global:
    # Used by qthelpers to close widgets after a defined time
    - TEST_CI="True"
    # Environment variables used by astropy helpers
    - CONDA_CHANNELS="conda-forge spyder-ide"
    - CONDA_DEPENDENCIES="anaconda-client pillow pytest pytest-cov pyyaml qtawesome qtpy requests"
    - PIP_DEPENDENCIES="coveralls pytest-qt"

matrix:
  include:
    # Qt4
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=2.7 USE_QT_API=PyQt4
#    - os: osx
#      language: generic
#      env: TRAVIS_PYTHON_VERSION=3.4 USE_QT_API=PyQt4
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.5 USE_QT_API=PyQt4
    # Qt5
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=2.7 USE_QT_API=PyQt5
#    - os: osx
#      language: generic
#      env: TRAVIS_PYTHON_VERSION=3.4 USE_QT_API=PyQt5
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.5 USE_QT_API=PyQt5

install:
  # Use Astropy ci helpers for initial setup
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh
  # Install the selected Qt version
  - if [[ "$USE_QT_API" == "PyQt5" ]]; then
      $CONDA_INSTALL qt5 pyqt5;
    elif [[ "$USE_QT_API" == "PyQt4" ]]; then
      $CONDA_INSTALL qt pyqt;
    fi
  - python setup.py install

script:
  - conda-manager

after_success:
  - coveralls

