env:
  - TRAVIS_PYTHON_VERSION=2.7
  - TRAVIS_PYTHON_VERSION=3.4
  - TRAVIS_PYTHON_VERSION=3.5

command:
  - env | sort
  - export TEST_CI="True"
  - export CONDA_CHANNELS="conda-forge spyder-ide"
  - export CONDA_DEPENDENCIES="anaconda-client pillow pytest pytest-cov pyyaml qtawesome qtpy requests"
  - export PIP_DEPENDENCIES="coveralls pytest-qt"
  - export TRAVIS_OS_NAME="linux"
  - echo $PYTHON_VERSION
  # Use Astropy ci helpers for initial setup
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

