env:
  - TRAVIS_PYTHON_VERSION=2.7
  - TRAVIS_PYTHON_VERSION=3.4
  - TRAVIS_PYTHON_VERSION=3.5

command:
  # Use Astropy ci helpers for initial setup
  - if [ ! -d "ci-helpers" ]; then
      git clone git://github.com/astropy/ci-helpers.git;
    fi
  - source ci-helpers/travis/setup_conda_linux.sh  # Use linux script
  - # Install package on test environment
  - PATH="$HOME/miniconda/bin:$PATH" /home/ubuntu/miniconda/envs/test/bin/python setup.py install 
  - # Run program
  - PATH="$HOME/miniconda/bin:$PATH" /home/ubuntu/miniconda/envs/test/bin/conda-manager
  - # Run tests
  - # Clean for the next test
  - PATH="$HOME/miniconda/bin:$PATH" /home/ubuntu/miniconda/bin/conda remove --name test --all
  - if [ -d "/home/ubuntu/miniconda" ]; then
      rm -rf /home/ubuntu/miniconda;
    fi

